# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
                ('town_or_city', models.CharField(max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('county_or_province_or_state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Artifact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Order')),
            ],
        ),
    ]
