# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-03 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='bid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
