# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200103_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
