# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_orderlineitem_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='owner_id',
            field=models.CharField(max_length=10),
        ),
    ]
