# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-03 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_category_description'),
        ('artifacts', '0002_artifact_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='category',
        ),
        migrations.AddField(
            model_name='artifact',
            name='category_id',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
