# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_artifact_sold_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='sold_out',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
