# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(default=''),
        ),
    ]
