# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20191227_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
    ]
