# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlineitem',
            old_name='review_owner',
            new_name='review_owner_id',
        ),
        migrations.AddField(
            model_name='reviewlineitem',
            name='review_owner_name',
            field=models.CharField(default='Admin', max_length=20),
        ),
    ]
