# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200110_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlineitem',
            name='review_owner_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reviewlineitem',
            name='review_owner_name',
            field=models.CharField(max_length=20),
        ),
    ]
