# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200110_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlineitem',
            name='review_owner_name',
            field=models.CharField(max_length=50),
        ),
    ]
