# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-22 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        ('artifacts', '0006_auto_20200106_1506'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_purchased', models.BooleanField(default=False)),
                ('bid_event_deadline', models.DateTimeField(null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='BidLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_quantity', models.IntegerField(default=1)),
                ('bid_note', models.CharField(default='No note', max_length=100)),
                ('bid_highest', models.BooleanField(default=False)),
                ('bid_paid', models.BooleanField(default=False)),
                ('bid_date_time', models.DateTimeField(null=True)),
                ('bid_archived', models.BooleanField(default=False)),
                ('bid_event', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bids.BidEvent')),
                ('bid_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
