# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-12 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='highest_bid',
        ),
    ]
