# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidlineitem',
            name='bid_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidEvent'),
        ),
    ]
