# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-12 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20191212_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='BidEvent',
        ),
    ]
