# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20191212_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlineitem',
            name='bid_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
