# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_bidlineitem_bid_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidevent',
            name='bid_event_status',
            field=models.CharField(choices=[('Bidding Open', 'Bidding Open'), ('Bidding Closed', 'Bidding Closed'), ('Bidding Not Available', 'Bidding Not Available')], default='Bidding Not Available', max_length=50),
        ),
    ]
