# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_bidlineitem_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlineitem',
            name='bid_highest',
            field=models.BooleanField(default=False),
        ),
    ]
