# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_bidlineitem_bid_highest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidevent',
            name='bid_event_deadline',
            field=models.DateField(null=True),
        ),
    ]
