# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0010_auto_20191227_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlineitem',
            name='bid_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
