# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0011_bidlineitem_bid_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlineitem',
            name='bid_paid',
            field=models.BooleanField(default=False),
        ),
    ]
