# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0012_bidlineitem_bid_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlineitem',
            name='bid_archived',
            field=models.BooleanField(default=False),
        ),
    ]
