# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-06 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0013_bidlineitem_bid_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidevent',
            name='bid_event_status',
        ),
        migrations.RemoveField(
            model_name='bidevent',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='bidevent',
            name='artifact_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
