# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0014_auto_20200106_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlineitem',
            name='bid_note',
            field=models.CharField(default='No note', max_length=100),
        ),
    ]
