# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-03 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyevent',
            old_name='history',
            new_name='history_id',
        ),
    ]
