# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-04 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_auto_20191203_0730'),
        ('histories', '0002_auto_20191203_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyevent',
            name='artifact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artifacts.Artifact'),
        ),
    ]
