# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-04 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0003_historyevent_artifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyevent',
            name='artifact',
        ),
    ]
