# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0006_auto_20191212_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyevent',
            name='event_era',
            field=models.CharField(choices=[('Gregorian', (('BC', 'BC'), ('AC', 'AC'))), ('Ages', (('bronze', 'Bronze Age'), ('iron', 'Iron Age'), ('middle', 'Middle Age'), ('atomic', 'Atomic Age'), ('space', 'Space Age'), ('information', 'Information Age'))), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=30),
        ),
    ]
